services:
  - type: web
    name: stockmanager
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn stockmanagerApp.wsgi:application --chdir backend
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: stockmanagerApp.settings
