services:
  - type: web
    name: stockmanager
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn stockmanagerApp.wsgi:application --chdir backend
    workingDir: backend
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: stockmanagerApp.settings
