services:
  - type: web
    name: stockmanager
    env: python
    buildCommand: pip install -r requirements.txt && cd backend && python manage.py collectstatic --noinput
    startCommand: cd backend && python manage.py migrate && gunicorn stockmanagerApp.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: stockmanagerApp.settings
