services:
  - type: web
    name: stockmanager
    env: python
    buildCommand: ""
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
